<?php

$fullname = $uname = $password = $cfpassword = $email = $phoneNumber = "";
$er_fullname = $er_uname = $er_password = $er_cfpassword = $er_email = $er_phoneNumber = "";

if (isset($_POST['register'])) {

    //$fullname = $_POST['fullname'];

    if (empty(trim($_POST['fullname']))) {
        $er_fullname = "<span style='color:red;'> Name is Required </span>";
    } else {
        $fullname = htmlspecialchars($_POST['fullname']);
    }




    if (empty(trim($_POST['uname']))) {
        $er_uname = "<span style='color:red;'> Username is Required </span>";
    } elseif (strpos($_POST['uname'], " ")) {
        $er_uname = "<span style='color:red;'> Space is not Allowed </span>";
    } elseif (strlen($_POST['uname']) < 6) {
        $er_uname = "<span style='color:red;'>Username must contain at least 6 characters </span>";
    } else {
        $uname = htmlspecialchars($_POST['fullname']);
    }


    //password validation






    //     4.	Email should be validated with php. Conditions must contain @ and at least one .(dot) after @

    //email 

    if (empty(trim($_POST['email']))) {
        $er_email = "<span style='color:red;'> Email is Required </span>";
    } elseif (strpos($_POST['email'], " ")) {
        $er_email = "<span style='color:red;'> Space is not Allowed </span>";
    } elseif (!strpos($_POST['email'], "@")) {
        $er_email = "<span style='color:red;'> Email is not valid.No [@] </span>";
    } elseif (strpos($_POST['email'], "@")) {
        $atRatePos = strpos($_POST['email'], "@");
        $te = $_POST['email'];
        $tempEmail = "";

        // for ($i = 0; $i < $atRatePos; $i++) {
        //     $tempEmail = $tempEmail + $te[$i];
        // }

        echo $tempEmail;

        if (strpos($tempEmail, ".")) {
            $email = htmlspecialchars($_POST['email']);
        } else {
            $er_email = "<span style='color:red;'> Email is not valid </span>";
        }
    }





    // 5.	Date fields’ options should be generated by loop.



    // 6.	Phone number fields will only accept numeric value.

    if (empty(trim($_POST['phoneNumber']))) {
        $er_phoneNumber = "<span style='color:red;'> phoneNumber is Required </span>";
    } elseif (!is_numeric($_POST['phoneNumber'])) {
        $er_phoneNumber = "<span style='color:red;'> Number is not valid (only numeric) </span>";
    } elseif (strpos($_POST['phoneNumber'], " ")) {
        $er_email = "<span style='color:red;'> Space is not Allowed </span>";
    } else {
        $phoneNumber = $_POST['phoneNumber'];
    }


    // 7.	Password must contain at least 8 character, 1 special character(only check # or ?),1 number and combination of uppercase and lowercase alphabet.
    // 8.	After occurrence of error proper error message should be shown.



    //password validation 

    if (empty(trim($_POST['password']))) {
        $er_fullname = "<span style='color:red;'> password is Required </span>";
    } elseif (strlen($_POST['password']) < 8) {
        $er_password = "<span style='color:red;'>Password must contain at least 8 character </span>";
    } elseif (!strpos($_POST['password'], "#")) {
        $er_password = "<span style='color:red;'>Password must contain 1 special character </span>";
    } elseif (!strpos($_POST['password'], "1")) {
        $er_password = "<span style='color:red;'>Password must contain 1 number  </span>";
    } elseif (!ctype_upper($_POST['password'], "1")) {
        $er_password = "<span style='color:red;'>Password must contain 1 uppercase  </span>";
    } elseif (!ctype_lower($_POST['password'], "1")) {
        $er_password = "<span style='color:red;'>Password must contain 1 lowercase  </span>";
    } else {
        $password = htmlspecialchars($_POST['password']);
    }

    if ($password == $_POST['cfpassword']) {
        $er_cfpassword = "<span style='color:red;'>Password does not match</span>";
    }
    else{
        $cfpassword = $_POST['cfpassword'];
    }
}

?>




<!DOCTYPE html>
<html>

<head>

    <title>Lab Task 4</title>
</head>

<body>

    <form action="" method="post">

        <fieldset>
            <legend>
                <h1>Club Member Registration</h1>
            </legend>

            <h3>All Fields are Required</h3>
            <table>
                <tr>
                    <td>Name: </td>
                    <td>
                        <input type="text" name="fullname" id=""> <?php echo $er_fullname; ?>
                    </td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td>
                        <input type="text" name="uname" id=""> <?php echo $er_uname; ?>
                    </td>
                </tr>

                <tr>
                    <td>Password</td>
                    <td>
                        <input type="text" name="password" id=""> <?php echo $er_fullname; ?>
                    </td>
                </tr>
                <tr>
                    <td>Confirm Password</td>
                    <td>
                        <input type="text" name="cfpassword" id=""> <?php echo $er_cfpassword; ?>
                    </td>
                </tr>

                <tr>
                    <td>Email</td>
                    <td>
                        <input type="text" name="email" id="">
                    </td>
                </tr>

                <tr>
                    <td>Phone</td>
                    <td>
                        <input type="text" name="code" id="" placeholder="code">-
                        <input type="text" name="phoneNumber" id="" placeholder="Number">
                    </td>
                </tr>

                <tr>
                    <td>Address</td>
                    <td>
                        <input type="text" name="address" id="" placeholder="Street Address"> 
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                        <input type="text" name="" id="" placeholder="City"> -
                        <input type="text" name="" id="" placeholder="State">
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                        <input type="text" name="" id="" placeholder="Postal">
                    </td>
                </tr>

                <tr>
                    <td>Birth Date: </td>
                    <td>

                        <select name="Day" id="">
                            <option value="Day" disabled selected>Day</option>

                            <?php
                            for ($i = 1; $i <= 31; $i++) {
                                echo "<option value='$i'>$i</option>";
                            }
                            ?>
                            <!-- <option value="1">1</option>
                            <option value="2">2</option> -->
                        </select>

                        <select name="Month" id="">
                            <option value="Month" disabled selected>Month</option>

                            <?php
                            $months = ['January', 'February', 'March', 'April', 'June', 'July', 'August', 'Sep', 'Oct', 'Nov', 'Dec'];

                            foreach ($months as $month) {
                                echo "<option value='$month'>$month</option>";
                            }
                            ?>
                            <!-- <option value="January">January</option>
                            <option value="February">February</option> -->
                        </select>

                        <select name="Year" id="">
                            <option value="Year" disabled selected>Year</option>

                            <?php
                            for ($i = 1995; $i <= 2000; $i++) {
                                echo "<option value='$i'>$i</option>";
                            }
                            ?>

                        </select>
                    </td>
                </tr>

                <tr>
                    <td>Gender: </td>
                    <td>
                        <input type="radio" name="gender" id="" value="Male">Male
                        <input type="radio" name="gender" id="" value="Female">Female
                    </td>
                </tr>

                <tr>
                    <td>
                        Where Did you hear about us?
                    </td>

                    <td>
                        <input type="checkbox" name="" id="" value="A Friend or Colleague">A Friend or Colleague <br>
                        <input type="checkbox" name="" id="" value="Google">Google <br>
                        <input type="checkbox" name="" id="" value="Blog Post"> Blog Post <br>
                        <input type="checkbox" name="" id="" value="News Atricle"> News Atricle <br>
                    </td>
                </tr>

                <tr>
                    <td>
                        Bio:
                    </td>
                    <td>
                        <textarea name="" id="" cols="30" rows="10"></textarea>
                    </td>
                </tr>

                <tr>
                    <td></td>

                    <td>
                        <input type="submit" name="register" id="" value="Register">
                    </td>
                </tr>
            </table>
        </fieldset>
    </form>
</body>

</html>