<?php

$fullname = $uname = $password = $cfpassword = $email = $phoneNumber = $hearFrom = $bod =  $gender = $street = $city = $state = $postal = $bio = $day = $month = $year = $phoneCode = "";
$er_fullname = $er_uname = $er_password = $er_cfpassword = $er_email = $er_phoneNumber = $er_bod = $er_hearFrom = $er_gender = $er_street = $er_city = $er_state = $er_postal = $er_bio = $er_phoneCode = "";

$hasError = false;

if (isset($_POST['register'])) {



    //fullname validation

    if (empty(trim($_POST['fullname']))) {
        $er_fullname = "<span style='color:red;'> Name is Required </span>";
        $hasError = true;
    } else {
        $fullname = htmlspecialchars($_POST['fullname']);
        $hasError = false;
    }



    //username validation

    if (empty(trim($_POST['uname']))) {
        $er_uname = "<span style='color:red;'> Username is Required </span>";
        $hasError = true;
    } elseif (strpos($_POST['uname'], " ")) {
        $er_uname = "<span style='color:red;'> Space is not Allowed </span>";
        $hasError = true;
    } elseif (strlen($_POST['uname']) < 6) {
        $er_uname = "<span style='color:red;'>Username must contain at least 6 characters </span>";
        $hasError = true;
    } else {
        $uname = htmlspecialchars($_POST['uname']);
        $hasError = false;
    }



    //password validation 

    if (empty(trim($_POST['password']))) {
        $er_password = "<span style='color:red;'> Password is Required </span>";
        $hasError = true;
    } elseif (strlen($_POST['password']) < 8) {
        $er_password = "<span style='color:red;'>Password must contain at least 8 character </span>";
        $hasError = true;
    } elseif (!strpos($_POST['password'], "#")) {
        $er_password = "<span style='color:red;'>Password must contain 1 special character </span>";
        $hasError = true;
    } elseif (!strpos($_POST['password'], "1")) {
        $er_password = "<span style='color:red;'>Password must contain 1 number  </span>";
        $hasError = true;
    }
    // } elseif (!ctype_upper($_POST['password'])) {
    //     $er_password = "<span style='color:red;'>Password must contain 1 uppercase  </span>";
    // } elseif (!ctype_lower($_POST['password'])) {
    //     $er_password = "<span style='color:red;'>Password must contain 1 lowercase  </span>";
    // } 
    else {
        $password = htmlspecialchars($_POST['password']);
        $hasError = false;
    }


    //confirm password validation

    if ($password != $_POST['cfpassword']) {
        $er_cfpassword = "<span style='color:red;'>Password does not match</span>";
        $hasError = true;
    } else {
        $cfpassword = $_POST['cfpassword'];
        $hasError = false;
    }


    //email validation

    if (empty(trim($_POST['email']))) {
        $er_email = "<span style='color:red;'> Email is Required </span>";
        $hasError = true;
    } elseif (strpos($_POST['email'], " ")) {
        $er_email = "<span style='color:red;'> Space is not Allowed </span>";
        $hasError = true;
    } elseif (!strpos($_POST['email'], "@") or !strpos($_POST['email'], ".")) {
        $er_email = "<span style='color:red;'> Email is not valid. No [@] </span>";
        $hasError = true;
    } elseif (strpos($_POST['email'], "@")) {
        $atRatePos = strpos($_POST['email'], "@");

        $tempEmail = $_POST['email'];
        $hasDot = false;

        for ($i = $atRatePos; $i < strlen($tempEmail); $i++) {
            if ($tempEmail[$i] == ".") {
                $hasDot = true;
                break;
            }
        }

        if ($hasDot) {
            $email = htmlspecialchars($_POST['email']);
            $hasError = false;
        } else {
            $er_email = "<span style='color:red;'> Email is not valid </span>";
            $hasError = true;
        }
    }



    //address 

    //street

    if (empty(trim($_POST['street']))) {
        $er_street = "<span style='color:red;'> Street is Required </span>";
        $hasError = true;
    } else {
        $street = htmlspecialchars($_POST['street']);
        $hasError = false;
    }

    //city

    if (empty(trim($_POST['city']))) {
        $er_city = "<span style='color:red;'> city is Required </span>";
        $hasError = true;
    } else {
        $city = htmlspecialchars($_POST['city']);
        $hasError = false;
    }

    //state

    if (empty(trim($_POST['state']))) {
        $er_state = "<span style='color:red;'>state is Required </span>";
        $hasError = true;
    } else {
        $state = htmlspecialchars($_POST['state']);
        $hasError = false;
    }

    //postal validation


    if (empty(trim($_POST['postal']))) {
        $er_postal = "<span style='color:red;'> postal is Required </span>";
        $hasError = true;
    } else {
        $postal = htmlspecialchars($_POST['postal']);
        $hasError = false;
    }




    // 5.	Date fields’ options should be generated by loop.



    // 6.	Phone number fields will only accept numeric value.

    if (empty(trim($_POST['phoneNumber']))) {
        $er_phoneNumber = "<span style='color:red;'> Phone Number is Required </span>";
        $hasError = true;
    } elseif (!is_numeric($_POST['phoneNumber'])) {
        $er_phoneNumber = "<span style='color:red;'> Number is not valid (only numeric) </span>";
        $hasError = true;
    } elseif (strpos($_POST['phoneNumber'], " ")) {
        $er_phoneNumber = "<span style='color:red;'> Space is not Allowed </span>";
        $hasError = true;
    } else {
        $phoneNumber = $_POST['phoneNumber'];
        $hasError = false;
    }

    //country code

    if (empty(trim($_POST['phone-code']))) {
        $er_phoneCode = "<span style='color:red;'> Phone Code is Required </span>";
        $hasError = true;
    } elseif (!is_numeric($_POST['phone-code'])) {
        $er_phoneCode = "<span style='color:red;'> Number is not valid (only numeric) </span>";
        $hasError = true;
    } elseif (strpos($_POST['phone-code'], " ")) {
        $er_phoneCode = "<span style='color:red;'> Space is not Allowed </span>";
        $hasError = true;
    } else {
        $phoneCode = $_POST['phone-code'];
        $hasError = false;
    }


    // 7.	Password must contain at least 8 character, 1 special character(only check # or ?),1 number and combination of uppercase and lowercase alphabet.
    // 8.	After occurrence of error proper error message should be shown.


    //bod

    if (!isset($_POST['Day']) or !isset($_POST['Month']) or !isset($_POST['Year'])) {
        $er_bod = "<span style='color:red;'> Select All Fields </span>";
        $hasError = true;
    } else {
        $day = htmlentities($_POST['Day']);
        $month = htmlentities($_POST['Month']);
        $year = htmlentities($_POST['Year']);
        $hasError = false;
    }




    //gender

    if (!isset($_POST['gender'])) {
        $er_gender = "<span style='color:red;'> (Must Select 1) </span>";
        $hasError = true;
    } else {
        $gender = $_POST['gender'];
        $hasError = false;
    }



    //hear from

    if (!isset($_POST['hear-from'])) {
        $er_hearFrom = "<span style='color:red;'> (Must Select 1) </span>";
        $hasError = true;
    } else {
        $hearFrom = $_POST['hear-from'];
        $hasError = false;
    }


    //bio validation

    if (empty(trim($_POST['bio']))) {
        $er_bio = "<span style='color:red;'>Bio is Required </span>";
        $hasError = true;
    } else {
        $bio = htmlspecialchars($_POST['bio']);
        $hasError = false;
    }
}

echo $hasError;

if (!$hasError) {
    echo "Name: $fullname" . "<br>";
    echo "Username: $uname" . "<br>";
    echo "Password: $password" . "<br>";
    echo "Confirm Password: $cfpassword" . "<br>";
    echo "Confirm Password: $cfpassword" . "<br>";
    echo "Phone Number: $phoneCode $phoneNumber" . "<br>";
    echo "Adree: Street - $street,  City - $city, State - $state, Postal Code - $postal" . "<br>";
    echo "Birthdate: $day/$month/$year" . "<br>";
    echo "Gender: $gender" . "<br>";
    echo "Where Did you hear about us?: ";
    echo "<pre>";
    print_r($hearFrom);
    echo "</pre>" . "<br>";

    echo "BIO: $bio" . "<br>";
}
